version: "3.8"

services:
  nextj:
    build: .
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=filtertube-pro.casantosmu.com,www.filtertube-pro.casantosmu.com
      - LETSENCRYPT_HOST=filtertube-pro.casantosmu.com,www.filtertube-pro.casantosmu.com
    expose:
      - "3000"
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
